Test shell expansion, redirection, and GitHub devices
Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>

diff --git a/.github/actions/test/action.yml b/.github/actions/test/action.yml
--- a/.github/actions/test/action.yml
+++ b/.github/actions/test/action.yml
@@ -47,8 +47,26 @@ runs:
       shell: bash --noprofile --norc -eo pipefail -x {0}
       run: |
         ls -al /dev/
-        echo "Hello, World!" >/dev/stdout
-        echo "Hello, World!" >/dev/stderr
+
+        echo "Testing stdout" >&1
+        echo "Testing stderr" >&2
+        echo "Testing stdout" >/dev/stdout
+        echo "Testing stderr" >/dev/stderr
+
+        echo "Testing stdout" 1> >(tee "$HOME"/stdout)
+        echo "Testing stderr" 2> >(tee "$HOME"/stderr)
+
+        echo GITHUB_ENV=$GITHUB_ENV
+        echo "test=GITHUB_ENV" | tee -a $GITHUB_ENV
+
+        echo GITHUB_OUTPUT=$GITHUB_OUTPUT
+        echo "test=GITHUB_OUTPUT" | tee -a $GITHUB_OUTPUT
+
+        echo GITHUB_STEP_SUMMARY=$GITHUB_STEP_SUMMARY
+        echo "Testing GITHUB_STEP_SUMMARY" | tee -a $GITHUB_STEP_SUMMARY
+
+        node -e "console.log('Testing console.log')" 1> >(tee -a $GITHUB_STEP_SUMMARY)
+        node -e "console.error('Testing console.error')" 2> >(tee -a $GITHUB_STEP_SUMMARY)
 
     - name: Check networking
       shell: bash --noprofile --norc -eo pipefail -x {0}
